micronaut:
  application:
    name: travellog
  server:
    cors:
      enabled: true

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'thisispassword'
    driverClassName: 'org.postgresql.Driver'
jpa:
  default:
    packages-to-scan:
      - 'com.kodality.travellog'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
endpoints:
  liquibase:
    enabled: true
    sensitive: false